export const environment = {
  production: false,
  staging: true,
  apiCerberoUrl: 'https://cerbero.pulzo.com/cerbero/v2',
  //apiCerberoUrl: 'https://stage-cerberos.pulzo.com/qa/cerbero/v2',
  cerberoFrontURL: 'http://localhost:4500',
  geaAppURL: 'http://localhost:4700',
  // geaAppURL: 'https://stage-comercial.pulzo.com',
  // cerberoFrontURL: 'https://stage-hub.pulzo.com',
  pageSize: 25,
  sentry: '',
  release: '2.5.1',
  secretKey: 'jbe4jb43hjb56oie5jtil34894',
  nameAppHub: 'ComercialApp',
};